#!/bin/bash
mkdir -p bin
chmod +x *
export MAIN_DIR=$PWD
echo "Which Server do you want to install?"
echo "Type [1] Java Server"
echo "Type [2] Bedrock Server"

read choiceForServer

# Ensure Java 21 is used
export JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64
export PATH=$JAVA_HOME/bin:$PATH

# If choice is 0 or null then run this command
if [[ -z $choiceForServer ]]; then
  echo "> Invalid Respond. Please try again."
  ./install

# If choice is 1 then run this command
elif [[ $choiceForServer == 1 ]]; then
  echo "> Running Java Installation..."
  ./installJava

# If choice is 2 then run this command
elif [[ $choiceForServer == 2 ]]; then
  echo "> Running Bedrock Installation..."
  ./installBedrock

else
  echo "> Invalid Respond. Please try again."
  ./install
fi

echo "> Installing AFK(Away From Keyboard) Script "
python3 -m pip install bpytop
echo ""
